{{- if .Values.configMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage.fullname" . }}-config
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap | nindent 2 }}
{{- end }}
