# Default values for backstage
# This is a YAML-formatted file.

# Image configuration
image:
  repository: ghcr.io/pdaxh/backstage-ulp
  tag: "latest"
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 7007

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: backstage.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource limits and requests
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Replica count
replicaCount: 1

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext: {}

# Container security context
securityContext: {}

# Image pull secrets
imagePullSecrets: []

# Name override
nameOverride: ""

# Full name override
fullnameOverride: ""

# Liveness and readiness probes
probes:
  livenessProbe:
    enabled: true
    path: /healthz
    port: 7007
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    enabled: true
    path: /healthz
    port: 7007
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Environment variables
env: {}

# ConfigMap data
configMap: {}

# Secret data
secret: {}

# Volume mounts
volumeMounts: []

# Volumes
volumes: []

# Service account
serviceAccount:
  create: true
  name: ""

# RBAC
rbac:
  create: true

# Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1

# Horizontal pod autoscaler
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
