# Production values for backstage
# Overrides default values.yaml

# Use production image tag
image:
  repository: ghcr.io/pdaxh/backstage-ulp
  tag: "latest"
  pullPolicy: Always

# Production ingress with TLS
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: backstage.ulp.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: backstage-tls
      hosts:
        - backstage.ulp.com

# Production resources
resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 1Gi

# Multiple replicas for production
replicaCount: 3

# Production environment variables
env:
  NODE_ENV: production
  BACKEND_URL: https://backstage.ulp.com

# Production security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

# Enable HPA for production
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

# Enable PDB for production
podDisruptionBudget:
  enabled: true
  minAvailable: 2
