# Development values for backstage
# Overrides default values.yaml

# Use development image tag
image:
  repository: ghcr.io/danielaxhammar/backstage-ulp
  tag: "dev"

# Enable ingress for development
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: backstage-dev.local
      paths:
        - path: /
          pathType: Prefix

# Development resources
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Single replica for development
replicaCount: 1

# Development environment variables
env:
  NODE_ENV: development
  BACKEND_URL: http://localhost:7007

# Enable debug logging
podAnnotations:
  backstage.io/debug: "true"
